import { describe, expect, it } from 'vitest';
import { TaskMemoV2ApplicationStore } from './taskMemoApplicationStore';
import { InMemoryRevisionServer } from './revisionModel';
import type { ApplicationJournalPersistence } from './applicationStore';
import type { AnonymousSnapshot } from './ownershipReconcile';
import { nodeFromV2Value } from './nodeV2Codec';
import { iphoneOwnershipRanks } from './fixtures/iphoneOwnershipRanks';
class Memory implements ApplicationJournalPersistence {
  value: string | null = null; journal: string | null = null; fail = false;
  loadCommitted = async () => this.value; loadJournal = async () => this.journal;
  writeCommitted = async (v: string) => { this.value = v; }; writeJournal = async (v: string) => { this.journal = v; };
  clearJournal = async () => { this.journal = null; };
  writeAtomic = async (expected: string | null, value: string) => { if (this.fail || this.value !== expected || this.journal) throw new Error('atomic failure'); this.value = value; };
}
const node = (id: string, rank: string) => ({ id, type: 'category', title: id, parentId: null, sortKey: rank, createdAt: '2026-10-02T00:00:00.000Z', updatedAt: '2026-10-02T00:00:00.000Z', deletedAt: null });
const source: AnonymousSnapshot = { scope: 'anonymous', nodes: { a: node('a', 'a0'), b: node('b', 'a1') }, profile: { body: '', ideasEnabled: false } };
const open = async (p = new Memory()) => ({ p, store: await TaskMemoV2ApplicationStore.open(p, [], { deviceId: 'account-device' }) });
describe('Phase D durable ownership application', () => {
  it('integrates the anonymized iPhone independent root/a0 pair without changing either original', async () => {
    const local = { ...iphoneOwnershipRanks.local, opaque: { keep: true }, routineHistory: { keep: [] }, deadlineSortKey: 'z9' };
    const account = iphoneOwnershipRanks.account;
    const p = new Memory();
    const store = await TaskMemoV2ApplicationStore.open(p, [nodeFromV2Value(account)], { deviceId: 'account-device' });
    const snapshot = { ...source, nodes: { [local.id]: local } };
    const original = JSON.stringify(snapshot);
    const ops = await store.commitOwnership(store.prepareOwnership(snapshot, 'accountA'), { [local.id]: 'local' });
    expect(ops).toHaveLength(1);
    expect(ops[0].payload.node).toEqual({ ...local, sortKey: 'a1' });
    expect(JSON.stringify(snapshot)).toBe(original);
    expect(store.nodes.find(n => n.id === account.id)?.sortKey).toBe('a0');
    const server = new InMemoryRevisionServer();
    await store.acknowledge(ops[0].opId, server.apply(ops[0]).record);
    expect(store.historyDepths.past).toBe(1);
    const restart = await TaskMemoV2ApplicationStore.open(p, [], { deviceId: 'account-device' });
    expect(restart.prepareOwnership(snapshot, 'accountA').items).toEqual([]);
    const edited = { ...snapshot, nodes: { [local.id]: { ...local, title: 'later local edit' } } };
    expect(restart.prepareOwnership(edited, 'accountA').items[0].kind).toBe('apply');
    await restart.undo(); expect(restart.nodes.find(n => n.id === local.id)?.deletedAt).toBeTruthy();
    await restart.redo(); expect(restart.nodes.find(n => n.id === local.id)?.sortKey).toBe('a1');
  });
  it('adopts anonymous-only legacy tombstones without confusing them with active deletions', async () => {
    const { store } = await open(); const server = new InMemoryRevisionServer();
    const tombstone = { ...node('deleted', 'c'), deletedAt: '2026-09-11T00:00:00.000Z', opaque: { keep: true } };
    const snapshot = { ...source, nodes: { deleted: tombstone } };
    const ops = await store.commitOwnership(store.prepareOwnership(snapshot, 'accountA'), { deleted: 'local' });
    expect(ops[0].payload.node).toEqual(tombstone);
    await store.acknowledge(ops[0].opId, server.apply(ops[0]).record);
    expect(store.nodes[0].sortKey).toBe('c'); expect(store.nodes[0].deletedAt).toBeTruthy();
    expect(store.historyDepths.past).toBe(1);
  });
  it('keeps adjusted ownership operations atomic and rejects changed previews', async () => {
    const p = new Memory();
    const account = iphoneOwnershipRanks.account, local = iphoneOwnershipRanks.local;
    const store = await TaskMemoV2ApplicationStore.open(p, [nodeFromV2Value(account)], { deviceId: 'account-device' });
    const snapshot = { ...source, nodes: { [local.id]: local } };
    const plan = store.prepareOwnership(snapshot, 'accountA'), before = p.value;
    p.fail = true;
    await expect(store.commitOwnership(plan, { [local.id]: 'local' })).rejects.toThrow('atomic');
    expect(p.value).toBe(before); expect(store.outbox).toEqual([]); expect(store.historyDepths.past).toBe(0);
    expect(store.nodes.map(n => n.id)).toEqual([account.id]);
    p.fail = false;
    await store.receive({ value: { ...account, title: 'remote edit' }, revision: 5, lastOpId: 'remote:5', lastDeviceId: 'remote', lastLocalSeq: 5, operationType: 'update' });
    await expect(store.commitOwnership(plan, { [local.id]: 'local' })).rejects.toThrow('変更');
    const fresh = store.prepareOwnership(snapshot, 'accountA');
    const ops = await store.commitOwnership(fresh, { [local.id]: 'local' });
    const server = new InMemoryRevisionServer();
    server.apply({ ...ops[0], opId: 'remote:6', deviceId: 'remote', ownership: undefined, payload: { node: { ...local, title: 'concurrent remote create' } } });
    expect(() => server.apply(ops[0])).toThrow('remote');
    expect(server.acknowledgement(ops[0].opId)).toBeUndefined();
    expect(store.historyDepths.past).toBe(0);
  });
  it('replans partial adjusted success without adopting accepted IDs twice and retains one History entry', async () => {
    const p = new Memory();
    const account = [node('cloud0', 'a0'), node('cloud1', 'a1')];
    const store = await TaskMemoV2ApplicationStore.open(p, account.map(n => nodeFromV2Value(n)), { deviceId: 'account-device' });
    const baseline = JSON.parse(p.value!).domain;
    const snapshot = { ...source, nodes: { a: node('a', 'a0'), b: node('b', 'a1') } };
    const server = new InMemoryRevisionServer();
    const ops = await store.commitOwnership(store.prepareOwnership(snapshot, 'accountA'), { a: 'local', b: 'local' });
    const accepted = server.apply(ops[0]).record!;
    await store.acknowledge(ops[0].opId, accepted); await store.markOwnershipConflict();
    const restart = await TaskMemoV2ApplicationStore.open(p, [], { deviceId: 'account-device' });
    const plan = await restart.reconfirmOwnership({ ...baseline, a: accepted }, { pinnedNote: null, features: null });
    expect(plan.items.map(i => i.id)).toEqual(['b']);
    const remaining = await restart.commitOwnership(plan, { b: 'local' });
    expect(remaining).toHaveLength(1); expect(remaining[0].targetNodeId).toBe('b');
    await restart.acknowledge(remaining[0].opId, server.apply(remaining[0]).record);
    expect(restart.historyDepths.past).toBe(1);
    expect(restart.prepareOwnership(snapshot, 'accountA').items).toEqual([]);
    expect(new Set(restart.nodes.map(n => n.sortKey)).size).toBe(4);
  });
  it('strict remote preconditions reject a concurrent account change, but normal sync still accepts differences', async () => {
    const { store } = await open(); const server = new InMemoryRevisionServer();
    const ops = await store.commitOwnership(store.prepareOwnership(source, 'accountA'), { a: 'local', b: 'local' });
    const remote = { ...ops[0], opId: 'another-device:1', deviceId: 'another-device', ownership: undefined, payload: { node: { ...node('a', 'a0'), title: 'Cloud' } } };
    server.apply(remote);
    expect(() => server.apply(ops[0])).toThrow('remote');
    expect(server.get('a')!.value.title).toBe('Cloud'); expect(server.acknowledgement(ops[0].opId)).toBeUndefined();
    expect(() => server.apply({ ...remote, opId: 'normal:2', baseRevision: 5 })).not.toThrow();
  });
  it('replans partial success on current remote without duplicating accepted targets', async () => {
    const { store } = await open(); const server = new InMemoryRevisionServer();
    const ops = await store.commitOwnership(store.prepareOwnership(source, 'accountA'), { a: 'local', b: 'local' });
    const a = server.apply(ops[0]).record!; await store.acknowledge(ops[0].opId, a);
    await store.markOwnershipConflict();
    const plan = await store.reconfirmOwnership({ a }, { pinnedNote: null, features: null });
    expect(plan.items.map(i => i.id)).toEqual(['b']);
    const next = await store.commitOwnership(plan, { b: 'local' });
    expect(next).toHaveLength(1); expect(next[0].targetNodeId).toBe('b');
    await store.acknowledge(next[0].opId, server.apply(next[0]).record);
    expect(store.historyDepths.past).toBe(1);
    expect(store.prepareOwnership(source, 'accountA').items).toEqual([]);
  });
  it('does not pretend partial remote application is completed or undoable', async () => {
    const { store, p } = await open();
    const plan = store.prepareOwnership(source, 'accountA');
    const ops = await store.commitOwnership(plan, { a: 'local', b: 'local' });
    expect(ops).toHaveLength(2); expect(store.historyDepths.past).toBe(0);
    const server = new InMemoryRevisionServer();
    await store.acknowledge(ops[0].opId, server.apply(ops[0]).record);
    expect(store.pendingOwnership?.appliedIds).toEqual([ops[0].opId]);
    const restart = (await open(p)).store;
    expect(restart.pendingOwnership).toBeDefined(); expect(restart.historyDepths.past).toBe(0);
    await expect(restart.command('edit', 'update', nodes => nodes)).rejects.toThrow();
    await restart.acknowledge(ops[1].opId, server.apply(ops[1]).record);
    expect(restart.pendingOwnership).toBeUndefined(); expect(restart.historyDepths.past).toBe(1);
    expect(restart.prepareOwnership(source, 'accountA').items).toEqual([]);
    await restart.undo(); expect(restart.nodes.every(n => n.deletedAt)).toBe(true);
    await restart.redo(); expect(restart.nodes.every(n => !n.deletedAt)).toBe(true);
  });
  it('skip retains source checkpoint and account B remains independent', async () => {
    const { store } = await open();
    await store.skipOwnership(source, 'accountA');
    expect(store.prepareOwnership(source, 'accountA').items).toEqual([]);
    expect(store.prepareOwnership(source, 'accountB').items).toHaveLength(2);
    expect(store.nodes).toEqual([]);
  });
  it('atomic failure and stale preview do not apply partially', async () => {
    const { p, store } = await open(); const plan = store.prepareOwnership(source, 'accountA');
    p.fail = true; await expect(store.commitOwnership(plan, { a: 'local', b: 'local' })).rejects.toThrow();
    expect(store.nodes).toEqual([]); expect(store.outbox).toEqual([]); expect(p.journal).toBeNull();
    p.fail = false; await store.skipOwnership(source, 'accountA');
    await expect(store.commitOwnership(plan, { a: 'local', b: 'local' })).rejects.toThrow();
  });
  it('a lost acknowledgement and failed receipt save survive restart without duplicate remote application', async () => {
    const { p, store } = await open(); const server = new InMemoryRevisionServer();
    const ops = await store.commitOwnership(store.prepareOwnership(source, 'accountA'), { a: 'local', b: 'local' });
    const first = server.apply(ops[0]); p.fail = true;
    await expect(store.acknowledge(ops[0].opId, first.record)).rejects.toThrow();
    expect(store.pendingOwnership?.appliedIds).toEqual([]); expect(store.historyDepths.past).toBe(0);
    p.fail = false; const restart = (await open(p)).store;
    expect(server.apply(ops[0]).record).toEqual(first.record);
    const plan = await restart.reconfirmOwnership({ a: first.record! }, { pinnedNote: null, features: null }, [ops[0].opId]);
    expect(plan.items.map(i => i.id)).toEqual(['b']);
    expect(JSON.parse(p.value!).ownershipRecoveryBackups[0].outbox).toHaveLength(2);
    const remaining = await restart.commitOwnership(plan, { b: 'local' });
    await restart.acknowledge(remaining[0].opId, server.apply(remaining[0]).record);
    expect(restart.historyDepths.past).toBe(1); expect(restart.pendingOwnership).toBeUndefined();
  });
  it('preserves complete Routine and unknown values and keeps separate account stores isolated', async () => {
    const a = await open(), b = await open(); const server = new InMemoryRevisionServer();
    const routine = { ...node('a', 'a0'), opaque: { nested: [1, null] }, routineHistory: { '2026-10-02': ['receipt'] }, routineDueOverrides: { '2026-10-03': null }, deadlineSortKey: 'z9' };
    const snapshot = { ...source, nodes: { a: routine } };
    const ops = await a.store.commitOwnership(a.store.prepareOwnership(snapshot, 'accountA'), { a: 'local' });
    expect(ops[0].payload.node).toEqual(routine);
    await a.store.acknowledge(ops[0].opId, server.apply(ops[0]).record);
    expect(b.store.nodes).toEqual([]); expect(b.store.outbox).toEqual([]); expect(b.store.historyDepths.past).toBe(0);
    expect(b.store.prepareOwnership(snapshot, 'accountB').items).toHaveLength(1);
    expect((await open(a.p)).store.prepareOwnership(snapshot, 'accountA').items).toEqual([]);
  });
  it('requires exact destructive confirmation and rejects purged adoption', async () => {
    const { store } = await open(); const server = new InMemoryRevisionServer();
    const first = await store.commitOwnership(store.prepareOwnership(source, 'accountA'), { a: 'local', b: 'local' });
    for (const op of first) await store.acknowledge(op.opId, server.apply(op).record);
    const deleted = { ...source, nodes: { ...source.nodes, a: { ...source.nodes.a, deletedAt: '2026-10-03T00:00:00.000Z' } } };
    const plan = store.prepareOwnership(deleted, 'accountA');
    await expect(store.commitOwnership(plan, { a: 'local' })).rejects.toThrow('明示確認');
    await expect(store.commitOwnership(plan, { a: 'local' }, { fingerprint: plan.fingerprint, deletedIds: ['b'] })).rejects.toThrow('明示確認');
    expect(store.nodes.every(n => !n.deletedAt)).toBe(true);
    const ops = await store.commitOwnership(plan, { a: 'local' }, { fingerprint: plan.fingerprint, deletedIds: ['a'] });
    await store.acknowledge(ops[0].opId, server.apply(ops[0]).record);
    const purged = { ...source, nodes: { ...source.nodes, b: { ...source.nodes.b, purgedAt: '2026-10-03T00:00:00.000Z' } } };
    await expect(store.commitOwnership(store.prepareOwnership(purged, 'accountA'), { a: 'account', b: 'local' })).rejects.toThrow('purged');
  });
});
