import { describe, expect, it } from 'vitest';
import type { Node } from '@/models/node';
import { categoryPath, DEADLINE_GROUPS, deadlineCreateContext, deadlineDraftForCreateContext, deadlineGroupForDueAt, deadlineGroups, moveMemoInDeadlineList, updateMemoDeadline } from './deadlineView';

const now = new Date(2026, 8, 13, 10);
const base = (id: string, dueAt: Date | null, parentId: string | null = null): Node => ({ id, type: 'memo', parentId, sortKey: id, title: id, body: '', dueAt, duePreset: dueAt ? 'custom' : 'none', status: 'active', completedAt: null, createdAt: now, updatedAt: now, deletedAt: null });

describe('deadline view', () => {
  it('各Memoを一つの期限グループだけに分類し、期限なしを最後にする', () => { const nodes = [base('late', new Date(2026, 8, 13, 9)), base('today', new Date(2026, 8, 13, 20)), base('tomorrow', new Date(2026, 8, 14, 12)), base('none', null)]; const groups = deadlineGroups(nodes, now); expect(groups.filter((group) => group.memos.length).map((group) => group.key)).toEqual(['overdue', 'today', 'tomorrow', 'none']); expect(groups.flatMap((group) => group.memos)).toHaveLength(4); });
  it('完了・削除Memoを除外し、グループ内を期限昇順にする', () => { const active = base('later', new Date(2026, 8, 13, 18)); const earlier = base('earlier', new Date(2026, 8, 13, 12)); const completed = { ...base('done', now), status: 'completed' as const, completedAt: now }; const deleted = { ...base('deleted', now), deletedAt: now }; expect(deadlineGroups([active, earlier, completed, deleted], now).flatMap((group) => group.memos).map((memo) => memo.id)).toEqual(['earlier', 'later']); });
  it('所属Categoryパスをcycle安全に構築する', () => { const root: Node = { id: 'a', type: 'category', parentId: null, sortKey: 'a', title: '個人', createdAt: now, updatedAt: now, deletedAt: null }; const child: Node = { ...root, id: 'b', parentId: 'a', title: '書籍' }; expect(categoryPath([root, child], 'b')).toBe('個人 > 書籍'); expect(categoryPath([{ ...root, parentId: 'a' }], 'a')).toBe('… > 個人'); });
  it.each([['morning', 'morning'], ['afternoon', 'afternoon'], ['today', 'today'], ['tomorrow', 'tomorrow'], ['thisWeek', 'thisWeek'], ['thisMonth', 'thisMonth'], ['thisYear', 'thisYear'], ['none', 'none']] as const)('%sへのdropで期限を確定時に変更する', (group, preset) => { const nodes = [base('memo', new Date(2026, 8, 20))]; const result = updateMemoDeadline(nodes, 'memo', group, now); const memo = result[0]; expect(memo.type === 'memo' && memo.duePreset).toBe(preset); if (memo.type === 'memo') { if (group === 'none') expect(memo.dueAt).toBeNull(); else expect(memo.dueAt).toBeInstanceOf(Date); } });
  it('今日と今月の締切時刻を設計どおり確定する', () => { const nodes = [base('memo', null)]; const today = updateMemoDeadline(nodes, 'memo', 'today', now)[0]; const month = updateMemoDeadline(nodes, 'memo', 'thisMonth', now)[0]; if (today.type !== 'memo' || month.type !== 'memo') throw new Error('memo expected'); expect(today.dueAt).toMatchObject({}); expect(today.dueAt?.getHours()).toBe(23); expect(today.dueAt?.getMinutes()).toBe(59); expect(month.dueAt?.getDate()).toBe(30); expect(month.dueAt?.getHours()).toBe(23); });
  it('グループ定義が＋表示・初期期限・編集可否の唯一の対応表になる', () => { expect(DEADLINE_GROUPS.map((definition) => { const context = deadlineCreateContext(definition, now); return [definition.id, context?.initialDuePreset ?? null, context?.dueEditable ?? null]; })).toEqual([['overdue', null, null], ['morning', 'morning', false], ['afternoon', 'afternoon', false], ['today', 'today', false], ['tomorrow', 'tomorrow', false], ['thisWeek', 'thisWeek', false], ['thisMonth', 'thisMonth', false], ['thisYear', 'thisYear', false], ['later', 'custom', true], ['none', 'none', false]]); });
  it('午前・午後presetを専用グループへ分類する', () => { const morning = { ...base('morning', new Date(2026, 8, 13, 12)), duePreset: 'morning' as const }; const afternoon = { ...base('afternoon', new Date(2026, 8, 13, 17)), duePreset: 'afternoon' as const }; expect(deadlineGroups([morning, afternoon], now).filter((group) => group.memos.length).map((group) => group.key)).toEqual(['morning', 'afternoon']); });
  it('非表示bucketをfallback先へ繰り上げてもMemoの期限データを変更しない', () => { const node = base('today', new Date(2026, 8, 13, 20)); if (node.type !== 'memo') throw new Error('memo expected'); const today = { ...node, duePreset: 'today' as const }; const originalDueAt = today.dueAt; const groups = deadlineGroups([today], now, new Set(['thisMonth'])); expect(groups.find((group) => group.key === 'thisMonth')?.memos).toEqual([today]); expect(today).toMatchObject({ duePreset: 'today', dueAt: originalDueAt }); });
  it('それ以降の＋は編集可能な初期期限を作り、一覧と同じ判定でそれ以降になる', () => { const definition = DEADLINE_GROUPS.find((group) => group.id === 'later'); if (!definition) throw new Error('later expected'); const context = deadlineCreateContext(definition, now); expect(context?.initialDueAt).toEqual(new Date(2027, 0, 1)); expect(deadlineGroupForDueAt(context!.initialDueAt, now)).toBe('later'); });
  it('それ以降のクイック追加を共通分類条件で検証する', () => { const definition = DEADLINE_GROUPS.find((group) => group.id === 'later'); const context = definition && deadlineCreateContext(definition, now); if (!context) throw new Error('context expected'); expect(deadlineDraftForCreateContext(context, new Date(2027, 0, 2), now)).toMatchObject({ duePreset: 'custom' }); expect(() => deadlineDraftForCreateContext(context, new Date(2026, 11, 31), now)).toThrow(/それ以降/); });
  it.each(['overdue', 'later'] as const)('%sはdrop不可でstateを変更しない', (group) => { const nodes = [base('memo', new Date(2026, 8, 20))]; expect(updateMemoDeadline(nodes, 'memo', group, now)).toBe(nodes); });
  it('dueAt同値ではsortKeyを第二キーにして安定ソートする', () => { const due = new Date(2026, 8, 13, 20); const a = { ...base('a', due), sortKey: 'a1' }; const b = { ...base('b', due), sortKey: 'a0' }; expect(deadlineGroups([a, b], now).find((group) => group.key === 'today')?.memos.map((memo) => memo.id)).toEqual(['b', 'a']); });
  it('同じ期限グループ内で短冊を指定位置へ並べ替える', () => { const a = base('a', new Date(2026, 8, 13, 12)); const b = base('b', new Date(2026, 8, 13, 18)); const moved = moveMemoInDeadlineList([a, b], 'b', 'today', 'a', now); expect(deadlineGroups(moved, now).find((group) => group.key === 'today')?.memos.map((memo) => memo.id)).toEqual(['b', 'a']); });
  it('期限グループをまたぐ移動で期限と挿入位置を同時に更新する', () => { const a = base('a', new Date(2026, 8, 13, 12)); const b = base('b', new Date(2026, 8, 14, 18)); const moved = moveMemoInDeadlineList([a, b], 'b', 'today', 'a', now); const today = deadlineGroups(moved, now).find((group) => group.key === 'today')?.memos; expect(today?.map((memo) => memo.id)).toEqual(['b', 'a']); expect(today?.[0].duePreset).toBe('today'); });
});
