import { describe, expect, it } from 'vitest';
import type { MemoNode } from '@/models/node';
import { applyRemoteDeletionsAsTombstones, mergeNodesByUpdatedAt, nodeFromFirestore, nodeToFirestore, withRemoteTombstones } from './firebaseNodeCodec';

const memo = (id: string, updatedAt: Date): MemoNode => ({ id, type: 'memo', parentId: null, sortKey: id, title: id, body: '', dueAt: null, duePreset: 'none', status: 'active', completedAt: null, createdAt: new Date(0), updatedAt, deletedAt: null });

describe('Firebase Node boundary', () => {
  it('Task/Idea種別をFirestore境界で往復し、旧MemoはTaskへ正規化する', () => { const idea = nodeFromFirestore('idea', nodeToFirestore({ ...memo('idea', new Date(1)), memoType: 'idea' })); const task = nodeFromFirestore('task', nodeToFirestore({ ...memo('task', new Date(1)), memoType: 'task' })); const legacy = nodeFromFirestore('legacy', nodeToFirestore(memo('legacy', new Date(1)))); expect(idea.type === 'memo' && idea.memoType).toBe('idea'); expect(task.type === 'memo' && task.memoType).toBe('task'); expect(legacy.type === 'memo' && legacy.memoType).toBe('task'); });
  it('Dateとrepeat ruleをFirestore境界で往復する', () => { const source = { ...memo('a', new Date('2026-01-02T03:04:05Z')), repeatRule: { frequency: 'week' as const, interval: 2, startsOn: '2026-01-02' } }; const encoded = nodeToFirestore(source); const decoded = nodeFromFirestore('a', encoded); expect(decoded.updatedAt).toEqual(source.updatedAt); expect(decoded.type).toBe('memo'); if (decoded.type === 'memo') expect(decoded.repeatRule).toEqual(source.repeatRule); });
  it('同じIDはupdatedAtが新しい側を採用し、片側だけのNodeを保持する', () => { const local = [memo('shared', new Date(20)), memo('local', new Date(10))]; const remote = [memo('shared', new Date(30)), memo('remote', new Date(10))]; const merged = mergeNodesByUpdatedAt(local, remote); expect(merged.map((node) => node.id).sort()).toEqual(['local', 'remote', 'shared']); expect(merged.find((node) => node.id === 'shared')?.updatedAt).toEqual(new Date(30)); });
  it('ローカル側が新しい場合はクラウド内容で上書きしない', () => { const merged = mergeNodesByUpdatedAt([memo('a', new Date(30))], [memo('a', new Date(20))]); expect(merged[0].updatedAt).toEqual(new Date(30)); });
  it('同一日のRoutine完了は端末間で重複せず日付キー1件へ統合する', () => { const local = { ...memo('a', new Date(30)), routineHistory: { '2026-09-17': '2026-09-17T01:00:00.000Z' } }; const remote = { ...memo('a', new Date(20)), routineHistory: { '2026-09-17': '2026-09-17T02:00:00.000Z' } }; const merged = mergeNodesByUpdatedAt([local], [remote])[0]; expect(merged.type === 'memo' && Object.keys(merged.routineHistory ?? {})).toEqual(['2026-09-17']); });
  it('新しい端末更新の完了取消tombstoneを古い完了履歴より優先する', () => { const cancelled = { ...memo('a', new Date(30)), routineHistory: { '2026-09-17': null } }; const completed = { ...memo('a', new Date(20)), routineHistory: { '2026-09-17': '2026-09-17T02:00:00.000Z' } }; const merged = mergeNodesByUpdatedAt([cancelled], [completed])[0]; expect(merged.type === 'memo' && merged.routineHistory?.['2026-09-17']).toBeNull(); });
  it('完全削除tombstoneは別端末のより新しい通常更新より優先する', () => { const purged = { ...memo('a', new Date(20)), deletedAt: new Date(20), purgedAt: new Date(20) }; const active = memo('a', new Date(30)); expect(mergeNodesByUpdatedAt([purged], [active])[0].purgedAt).toEqual(new Date(20)); expect(mergeNodesByUpdatedAt([active], [purged])[0].purgedAt).toEqual(new Date(20)); });
  it('完全削除tombstoneをFirestore境界でDateとして往復する', () => { const purged = { ...memo('a', new Date(20)), deletedAt: new Date(20), purgedAt: new Date(20) }; expect(nodeFromFirestore('a', nodeToFirestore(purged)).purgedAt).toEqual(new Date(20)); });
  it('ローカルから欠落したクラウドNodeを物理削除せずtombstoneにする', () => { const removed = memo('removed', new Date(10)); const kept = memo('kept', new Date(10)); const synchronized = withRemoteTombstones([kept], [kept, removed], new Date(20)); expect(synchronized.find((node) => node.id === 'removed')).toMatchObject({ deletedAt: new Date(20), purgedAt: new Date(20), updatedAt: new Date(20) }); });
  it('旧クライアントからの物理削除もtombstoneとして保持する', () => { const parent = memo('parent', new Date(10)); expect(applyRemoteDeletionsAsTombstones([parent], new Set(['parent']), new Date(20))[0]).toMatchObject({ deletedAt: new Date(20), purgedAt: new Date(20) }); });
  it('別端末が削除後に子を更新してもtombstoneを解除しない', () => { const childTombstone = { ...memo('child', new Date(20)), parentId: 'parent', deletedAt: new Date(20), purgedAt: new Date(20) }; const resentChild = { ...memo('child', new Date(30)), parentId: 'parent', title: '別端末の更新' }; expect(mergeNodesByUpdatedAt([childTombstone], [resentChild])[0]).toMatchObject({ purgedAt: new Date(20), title: 'child' }); });
});
