import { useEffect, useMemo, useRef, useState } from 'react';
import { KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';

import { NodeTree, type DropCandidate } from '@/components/NodeTree';
import { currentTreeTraceId, nodesRevision, summarizeNodes, treeDiagnosticLog } from '@/components/treeDiagnostics';
import { DeadlineView } from '@/components/DeadlineView';
import { DateTimeField } from '@/components/DateTimeField';
import { canMoveNode, completeMemo, createNode, createRoutineCategories, duplicateMemo, hardDeleteNode, moveMemos, moveNode, restoreMemo, restoreNode, softDeleteNode, tryMoveNode, updateNode } from '@/domain/nodeOperations';
import { categoryPath, deadlineGroupDefinitions, deadlineGroupForDueAt, moveMemoInDeadlineList, TODAY_GRANULARITIES, type DeadlineCreateContext, type DeadlineGroupKey, type TodayGranularity } from '@/domain/deadlineView';
import { commitNodeHistory, createNodeHistory, redoNodeHistory, replaceNodeHistory, undoNodeHistory } from '@/domain/nodeHistory';
import { mockNodes } from '@/data/mockNodes';
import type { DuePreset, MemoNode, Node } from '@/models/node';
import { loadNodes, normalizeLegacyRanks, resetNodes, saveNodes } from '@/services/nodeStorage';
import { exportNodesToFile, pickAndParseNodeBackup } from '@/services/nodeTransfer';
import { DEFAULT_LIST_DISPLAY_PREFERENCES, loadListDisplayPreferences, saveListDisplayPreferences } from '@/services/viewPreferences';
import { loadPinnedNote, savePinnedNote } from '@/services/pinnedNoteStorage';
import { dueDateForPreset, formatDateTimeInput, parseLocalDateTime } from '@/utils/dueDates';
import { useAppTheme, type ThemeColors, type ThemeMode } from '@/theme/theme';
import { COMPLETION_HISTORY_CRITERIA, completionHistoryGroups, type CompletionHistoryCriterion } from '@/domain/completionHistory';
import { appAlert } from '@/utils/appAlert';
import { useFirebaseSync } from '@/hooks/useFirebaseSync';
import { SyncAccountPanel } from '@/components/SyncAccountPanel';
import { routineCategoryForMemo, routineHistoryDays, toggleRoutineCompletion } from '@/domain/routine';

type Panel = 'completed' | 'trash' | null;
type MainView = 'tree' | 'deadline';
type Editor = { type: 'memo' | 'category'; node?: Node; parentId: string | null; dueContext?: DeadlineCreateContext } | null;
const presets: { key: DuePreset; label: string }[] = [{ key: 'none', label: '期限なし' }, { key: 'today', label: '今日中' }, { key: 'tomorrow', label: '明日中' }, { key: 'morning', label: '午前中' }, { key: 'afternoon', label: '午後まで' }, { key: 'thisWeek', label: '今週中' }, { key: 'thisMonth', label: '今月中' }, { key: 'thisYear', label: '今年中' }, { key: 'custom', label: '日時指定' }];

export default function HomeScreen() {
  const { colors, resolved, mode, setMode } = useAppTheme(); const styles = createStyles(colors);
  const [history, setHistory] = useState(() => createNodeHistory(mockNodes)); const nodes = history.nodes; const [ready, setReady] = useState(false);
  const [pinnedNote, setPinnedNote] = useState(''); const pinnedSaveQueue = useRef(Promise.resolve());
  const [visibleGroupIds, setVisibleGroupIds] = useState<Set<DeadlineGroupKey>>(() => new Set(DEFAULT_LIST_DISPLAY_PREFERENCES.visibleGroupIds)); const [showPinnedNote, setShowPinnedNote] = useState(true); const [todayGranularity, setTodayGranularity] = useState<TodayGranularity>(DEFAULT_LIST_DISPLAY_PREFERENCES.todayGranularity); const [pinnedNoteHeight, setPinnedNoteHeight] = useState(DEFAULT_LIST_DISPLAY_PREFERENCES.pinnedNoteHeight); const listDisplaySaveQueue = useRef(Promise.resolve());
  const [view, setView] = useState<MainView>('deadline'); const [deadlineExpanded, setDeadlineExpanded] = useState<Set<DeadlineGroupKey>>(() => new Set(deadlineGroupDefinitions(DEFAULT_LIST_DISPLAY_PREFERENCES.todayGranularity).map((group) => group.id))); const [settingsOpen, setSettingsOpen] = useState(false); const [syncOpen, setSyncOpen] = useState(false);
  const [panel, setPanel] = useState<Panel>(null); const [editor, setEditor] = useState<Editor>(null); const [menuNode, setMenuNode] = useState<Node | null>(null); const [createOpen, setCreateOpen] = useState(false); const [createParentId, setCreateParentId] = useState<string | null>(null); const [movingNode, setMovingNode] = useState<Node | null>(null); const [movingMemoIds, setMovingMemoIds] = useState<string[]>([]);
  const [exitingMemos, setExitingMemos] = useState<Map<string, MemoNode>>(() => new Map());
  const [completionNotices, setCompletionNotices] = useState<{ token: string; id: string; title: string }[]>([]);
  const sync = useFirebaseSync(nodes, ready, (cloudNodes) => { setHistory((current) => replaceNodeHistory(current, normalizeLegacyRanks(cloudNodes))); saveNodes(cloudNodes).catch(() => {}); });
  useEffect(() => {
    const traceId = currentTreeTraceId(); treeDiagnosticLog('hydrate/reload-start', { traceId, source: 'initial-mount' });
    Promise.all([loadNodes(mockNodes), loadPinnedNote(), loadListDisplayPreferences()]).then(([loaded, note, listDisplay]) => {
      treeDiagnosticLog('hydrate/reload-result', { traceId, source: 'initial-mount', nodesRevision: nodesRevision(loaded), nodes: summarizeNodes(loaded) });
      setHistory((current) => replaceNodeHistory(current, loaded)); setPinnedNote(note.body); setVisibleGroupIds(new Set(listDisplay.visibleGroupIds)); setShowPinnedNote(listDisplay.showPinnedNote); setTodayGranularity(listDisplay.todayGranularity); setPinnedNoteHeight(listDisplay.pinnedNoteHeight); setDeadlineExpanded(new Set(deadlineGroupDefinitions(listDisplay.todayGranularity).map((group) => group.id)));
    }).catch((error) => { treeDiagnosticLog('hydrate/reload-error', { traceId, message: error instanceof Error ? error.message : String(error) }); appAlert('読み込みエラー', '保存データを読み込めませんでした。'); }).finally(() => setReady(true));
  }, []);
  useEffect(() => {
    if (!ready) return;
    const traceId = currentTreeTraceId(); const revision = nodesRevision(nodes); const startedAt = Date.now();
    treeDiagnosticLog('persist-start', { traceId, nodesRevision: revision, nodes: summarizeNodes(nodes) });
    saveNodes(nodes).then(() => loadNodes([])).then((stored) => {
      treeDiagnosticLog('persist-success', { traceId, nodesRevision: revision, storedRevision: nodesRevision(stored), matchesCommittedState: nodesRevision(stored) === revision, elapsedMs: Date.now() - startedAt, storedNodes: summarizeNodes(stored) });
    }).catch((error) => { treeDiagnosticLog('persist-error', { traceId, nodesRevision: revision, elapsedMs: Date.now() - startedAt, message: error instanceof Error ? error.message : String(error) }); appAlert('保存エラー', '端末への保存に失敗しました。'); });
  }, [nodes, ready]);
  const parentName = (id: string | null) => id ? nodes.find((n) => n.id === id)?.title ?? 'ルート' : 'ルート';
  const displayNodes = useMemo(() => nodes.map((node) => exitingMemos.get(node.id) ?? node), [exitingMemos, nodes]);
  const apply = (label: string, operation: (current: Node[]) => Node[]) => { try { setHistory((current) => commitNodeHistory(current, label, operation)); } catch (error) { appAlert('操作できません', error instanceof Error ? error.message : '不明なエラー'); } };
  const replaceNodes = (operation: (current: Node[]) => Node[]) => { try { setHistory((current) => replaceNodeHistory(current, operation(current.nodes))); } catch (error) { appAlert('操作できません', error instanceof Error ? error.message : '不明なエラー'); } };
  const changePinnedNote = (body: string) => { setPinnedNote(body); pinnedSaveQueue.current = pinnedSaveQueue.current.then(() => savePinnedNote(body)).then(() => undefined).catch(() => undefined); };
  const saveListPreferences = (groups: Set<DeadlineGroupKey>, pinned: boolean, granularity: TodayGranularity, height: number) => { const value = { visibleGroupIds: [...groups], showPinnedNote: pinned, todayGranularity: granularity, pinnedNoteHeight: height }; listDisplaySaveQueue.current = listDisplaySaveQueue.current.then(() => saveListDisplayPreferences(value)).catch(() => undefined); };
  const changeListDisplay = (groups: Set<DeadlineGroupKey>, pinned: boolean, granularity = todayGranularity) => { setVisibleGroupIds(groups); setShowPinnedNote(pinned); setTodayGranularity(granularity); saveListPreferences(groups, pinned, granularity, pinnedNoteHeight); };
  const completeWithUndo = (memo: MemoNode) => { if (exitingMemos.has(memo.id)) return; setExitingMemos((current) => new Map(current).set(memo.id, memo)); apply('Memoを完了', (current) => completeMemo(current, memo.id)); };
  const finishCompletionAnimation = (id: string) => { const memo = exitingMemos.get(id); setExitingMemos((current) => { const next = new Map(current); next.delete(id); return next; }); if (memo) setCompletionNotices((current) => [...current, { token: `${id}-${Date.now()}`, id, title: memo.title }]); };
  const openCreate = (type: 'memo' | 'category') => { setCreateOpen(false); setMenuNode(null); setEditor({ type, parentId: createParentId }); };
  const onDrop = (nodeId: string, candidate: DropCandidate) => {
    const traceId = currentTreeTraceId();
    setHistory((current) => {
      const before = current.nodes.find((node) => node.id === nodeId); const next = commitNodeHistory(current, 'Nodeを移動', (nodes) => tryMoveNode(nodes, nodeId, candidate.parentId, candidate.beforeId)); const after = next.nodes.find((node) => node.id === nodeId);
      treeDiagnosticLog('drag-end-after-state', { traceId, movingId: nodeId, candidate, committed: next !== current, before: before ? { parentId: before.parentId, sortKey: before.sortKey } : null, after: after ? { parentId: after.parentId, sortKey: after.sortKey } : null, beforeNodesRevision: nodesRevision(current.nodes), nodesRevision: nodesRevision(next.nodes), nodes: summarizeNodes(next.nodes) });
      return next;
    });
  };
  const exportData = async () => { try { await exportNodesToFile(nodes); } catch (error) { appAlert('書き出しエラー', error instanceof Error ? error.message : 'データを書き出せませんでした。'); } };
  const importData = async () => { try { const imported = await pickAndParseNodeBackup(); if (!imported) return; appAlert('データを読み込む', `現在のデータを、選択した${imported.length}件のNodeで置き換えます。先に書き出しておくことを推奨します。`, [{ text: 'キャンセル', style: 'cancel' }, { text: '置き換える', style: 'destructive', onPress: async () => { try { const normalized = normalizeLegacyRanks(imported); await saveNodes(normalized); setHistory((current) => replaceNodeHistory(current, normalized)); setSettingsOpen(false); } catch { appAlert('保存エラー', '読み込んだデータを端末へ保存できませんでした。'); } } }]); } catch (error) { appAlert('読み込みエラー', error instanceof Error ? error.message : 'データを読み込めませんでした。'); } };
  const askDelete = (node: Node) => { setMenuNode(null); if (node.type === 'memo') appAlert('Memoを削除', `「${node.title}」をゴミ箱へ移動します。`, [{ text: 'キャンセル', style: 'cancel' }, { text: '削除', style: 'destructive', onPress: () => apply('Memoを削除', (n) => softDeleteNode(n, node.id)) }]); else appAlert('Categoryを削除', '子の扱いを選択してください。', [{ text: 'キャンセル', style: 'cancel' }, { text: 'Categoryのみ削除', onPress: () => apply('Categoryのみ削除', (n) => softDeleteNode(n, node.id, false)) }, { text: '子ごと削除', style: 'destructive', onPress: () => apply('Categoryを子ごと削除', (n) => softDeleteNode(n, node.id, true)) }]); };
  return <SafeAreaView style={styles.safeArea} edges={['top', 'right', 'bottom', 'left']}><StatusBar style={resolved === 'dark' ? 'light' : 'dark'} />
    <View style={styles.header}><View><Text style={styles.title}>TaskMemo</Text><Text style={styles.subtitle}>メモとタスク</Text></View><View style={styles.headerActions}><HistoryButton label="↶" accessibilityLabel="元に戻す" disabled={!history.past.length} onPress={() => setHistory(undoNodeHistory)} /><HistoryButton label="↷" accessibilityLabel="やり直す" disabled={!history.future.length} onPress={() => setHistory(redoNodeHistory)} /><TopButton label="設定" onPress={() => setSettingsOpen(true)} /></View></View>
    <View style={styles.tabs}><Tab label="一覧" active={view === 'deadline'} onPress={() => setView('deadline')} /><Tab label="ツリー" active={view === 'tree'} onPress={() => setView('tree')} /><Tab label="完了" onPress={() => setPanel('completed')} /><Tab label="ゴミ箱" onPress={() => setPanel('trash')} /></View>
    <View style={styles.tree} pointerEvents={ready ? 'auto' : 'none'}>{view === 'tree' ? <NodeTree nodes={displayNodes} completingIds={new Set(exitingMemos.keys())} onCompletionAnimationFinished={finishCompletionAnimation} onAddMemo={(parentId) => setEditor({ type: 'memo', parentId })} onEdit={(node) => setEditor({ type: node.type, node, parentId: node.parentId })} onComplete={completeWithUndo} onMenu={setMenuNode} onDrop={onDrop} onBulkMove={setMovingMemoIds} /> : <DeadlineView nodes={displayNodes} visibleGroupIds={visibleGroupIds} todayGranularity={todayGranularity} completingIds={new Set(exitingMemos.keys())} onCompletionAnimationFinished={finishCompletionAnimation} showPinnedNote={showPinnedNote} pinnedNote={pinnedNote} pinnedNoteHeight={pinnedNoteHeight} onPinnedNoteChange={changePinnedNote} onPinnedNoteHeightChange={(height) => { setPinnedNoteHeight(height); saveListPreferences(new Set(visibleGroupIds), showPinnedNote, todayGranularity, height); }} expandedGroups={deadlineExpanded} onExpandedGroupsChange={setDeadlineExpanded} onQuickAdd={(title, deadline) => apply('Memoをクイック追加', (current) => createNode(current, 'memo', { title, parentId: null, ...deadline }))} onEdit={(node) => setEditor({ type: 'memo', node, parentId: node.parentId })} onComplete={completeWithUndo} onMenu={setMenuNode} onDueDrop={(id, group, beforeId) => apply('一覧でMemoを移動', (current) => moveMemoInDeadlineList(current, id, group, beforeId, new Date(), todayGranularity))} />}</View>
    <Pressable disabled={!ready} style={[styles.fab, !ready && { opacity: 0.4 }]} onPress={() => { setCreateParentId(null); if (view === 'deadline') setEditor({ type: 'memo', parentId: null }); else setCreateOpen(true); }} accessibilityLabel="新規作成"><Text style={styles.fabText}>＋</Text></Pressable>
    <Sheet visible={createOpen} title="新規作成" onClose={() => setCreateOpen(false)}><Action label="Memo" onPress={() => openCreate('memo')} />{view === 'tree' && <><Action label="Category" onPress={() => openCreate('category')} /><Action label="ルーティーン一式" onPress={() => { apply('ルーティーンCategoryを作成', (current) => createRoutineCategories(current)); setCreateOpen(false); }} /></>}</Sheet>
    <Sheet visible={!!menuNode} title={menuNode?.title ?? ''} onClose={() => setMenuNode(null)}>
      <Action label="編集" onPress={() => { if (menuNode) setEditor({ type: menuNode.type, node: menuNode, parentId: menuNode.parentId }); setMenuNode(null); }} />
      {menuNode?.type === 'memo' ? <><Action label={menuNode.status === 'completed' ? '未完了へ戻す' : '完了'} onPress={() => { apply(menuNode.status === 'completed' ? 'Memoを未完了に戻す' : 'Memoを完了', (n) => menuNode.status === 'completed' ? restoreMemo(n, menuNode.id) : completeMemo(n, menuNode.id)); setMenuNode(null); }} />{routineCategoryForMemo(nodes, menuNode) && <><Text style={styles.settingsHeading}>直近7日の実績（タップで修正）</Text>{routineHistoryDays(menuNode).map((day) => <Action key={day.key} label={`${day.completed ? '✓' : '－'} ${day.key}`} onPress={() => { apply('ルーティーン実績を変更', (current) => toggleRoutineCompletion(current, menuNode.id, day.date)); setMenuNode(null); }} />)}</>}<Action label="複製" onPress={() => { apply('Memoを複製', (nodes) => duplicateMemo(nodes, menuNode.id)); setMenuNode(null); }} /></> : <Action label="子を追加" onPress={() => { if (menuNode) setCreateParentId(menuNode.id); setMenuNode(null); setCreateOpen(true); }} />}
      <Action label="移動" onPress={() => { setMovingNode(menuNode); setMenuNode(null); }} /><Action label="削除" danger onPress={() => menuNode && askDelete(menuNode)} />
    </Sheet>
    <EditorModal key={editor?.node?.id ?? `${editor?.type}-${editor?.parentId ?? 'root'}-${editor?.dueContext?.targetGroup ?? 'default'}`} editor={editor} nodes={nodes} onClose={() => setEditor(null)} onSave={(draft) => { apply(editor?.node ? 'Nodeを編集' : 'Nodeを作成', (current) => editor?.node ? updateNode(current, editor.node.id, draft) : createNode(current, editor!.type, draft)); setEditor(null); }} />
    <ListPanel type={panel} nodes={nodes} parentName={parentName} onClose={() => setPanel(null)} onRestore={(id, completed) => apply(completed ? 'Memoを未完了に戻す' : 'Nodeを復元', (n) => completed ? restoreMemo(n, id) : restoreNode(n, id))} onDelete={(id) => { const node = nodes.find((item) => item.id === id); if (node) askDelete(node); }} onHardDelete={(id) => appAlert('完全に削除', '完全に削除すると元に戻せません。', [{ text: 'キャンセル', style: 'cancel' }, { text: '完全に削除', style: 'destructive', onPress: () => replaceNodes((n) => hardDeleteNode(n, id)) }])} onReset={() => appAlert('データを初期化', '端末の変更を破棄して初期データへ戻します。', [{ text: 'キャンセル', style: 'cancel' }, { text: '初期化', style: 'destructive', onPress: async () => { await resetNodes(); setHistory((current) => replaceNodeHistory(current, normalizeLegacyRanks(mockNodes))); setPanel(null); } }])} />
    <MovePanel node={movingNode} nodes={nodes} onClose={() => setMovingNode(null)} onMove={(parentId) => { if (movingNode) apply('Nodeを移動', (n) => moveNode(n, movingNode.id, parentId)); setMovingNode(null); }} />
    <BulkMovePanel memoIds={movingMemoIds} nodes={nodes} onClose={() => setMovingMemoIds([])} onMove={(parentId) => { apply('Memoを一括移動', (current) => moveMemos(current, movingMemoIds, parentId)); setMovingMemoIds([]); }} />
    <Sheet visible={settingsOpen} title="設定" onClose={() => setSettingsOpen(false)}><Text style={styles.settingsHeading}>同期</Text><Action label={`クラウド同期: ${sync.status === 'synced' ? '同期済み' : sync.status === 'connecting' ? '接続中…' : sync.user ? 'オフライン/エラー' : sync.configured ? '未ログイン' : '未設定'}`} onPress={() => { setSettingsOpen(false); setSyncOpen(true); }} /><Text style={styles.settingsHeading}>外観</Text>{(['system', 'light', 'dark'] as ThemeMode[]).map((value) => <Action key={value} label={`${mode === value ? '●' : '○'} ${value === 'system' ? 'システム' : value === 'light' ? 'ライト' : 'ダーク'}`} onPress={() => setMode(value)} />)}<Text style={styles.settingsHeading}>今日の表示粒度</Text>{TODAY_GRANULARITIES.map((item) => <Action key={item.id} label={`${todayGranularity === item.id ? '●' : '○'}  ${item.label}`} onPress={() => { setDeadlineExpanded(new Set(deadlineGroupDefinitions(item.id).map((group) => group.id))); changeListDisplay(new Set(visibleGroupIds), showPinnedNote, item.id); }} />)}<Text style={styles.settingsHeading}>一覧の表示</Text>{deadlineGroupDefinitions(todayGranularity).map((group) => <Action key={group.id} label={`${visibleGroupIds.has(group.id) ? 'ON' : 'OFF'}  ${group.label}`} onPress={() => { const next = new Set(visibleGroupIds); if (next.has(group.id)) next.delete(group.id); else next.add(group.id); changeListDisplay(next, showPinnedNote); }} />)}<Action label={`${showPinnedNote ? 'ON' : 'OFF'}  上部の常設メモ`} onPress={() => changeListDisplay(new Set(visibleGroupIds), !showPinnedNote)} /><Text style={styles.settingsHeading}>データ管理</Text><Action label="データを書き出す" onPress={exportData} /><Action label="データを読み込む" onPress={importData} /></Sheet>
    <Sheet visible={syncOpen} title="クラウド同期" onClose={() => setSyncOpen(false)}><SyncAccountPanel configured={sync.configured} user={sync.user} status={sync.status} error={sync.error} onSignIn={sync.signIn} onSignUp={sync.signUp} onSignOut={sync.signOut} /></Sheet>
    <View pointerEvents="box-none" style={styles.snackbarStack}>{completionNotices.map((notice) => <SnackbarNotice key={notice.token} notice={notice} onExpire={() => setCompletionNotices((current) => current.filter((item) => item.token !== notice.token))} onUndo={() => { setExitingMemos((current) => { const next = new Map(current); next.delete(notice.id); return next; }); apply('完了を元に戻す', (current) => restoreMemo(current, notice.id)); setCompletionNotices((current) => current.filter((item) => item.token !== notice.token)); }} />)}</View>
  </SafeAreaView>;
}

function TopButton({ label, onPress }: { label: string; onPress: () => void }) { const styles = useStyles(); return <Pressable onPress={onPress} style={styles.topButton}><Text style={styles.topText}>{label}</Text></Pressable>; }
function HistoryButton({ label, accessibilityLabel, disabled, onPress }: { label: string; accessibilityLabel: string; disabled: boolean; onPress: () => void }) { const styles = useStyles(); return <Pressable disabled={disabled} accessibilityRole="button" accessibilityLabel={accessibilityLabel} accessibilityState={{ disabled }} onPress={onPress} style={[styles.historyButton, disabled && styles.disabled]}><Text style={styles.historyText}>{label}</Text></Pressable>; }
function Tab({ label, active, onPress }: { label: string; active?: boolean; onPress: () => void }) { const styles = useStyles(); return <Pressable onPress={onPress} style={[styles.tab, active && styles.tabActive]}><Text style={[styles.tabText, active && styles.tabTextActive]}>{label}</Text></Pressable>; }
function Action({ label, onPress, danger }: { label: string; onPress: () => void; danger?: boolean }) { const styles = useStyles(); return <Pressable onPress={onPress} style={styles.action}><Text style={[styles.actionText, danger && styles.danger]}>{label}</Text></Pressable>; }
function Sheet({ visible, title, onClose, children }: { visible: boolean; title: string; onClose: () => void; children: React.ReactNode }) { const styles = useStyles(); return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable style={styles.backdrop} onPress={onClose}><Pressable style={styles.sheet} onPress={(e) => e.stopPropagation()}><Text style={styles.sheetTitle}>{title}</Text><ScrollView style={styles.sheetContent}>{children}</ScrollView><Action label="キャンセル" onPress={onClose} /></Pressable></Pressable></Modal>; }

function EditorModal({ editor, nodes, onClose, onSave }: { editor: Editor; nodes: Node[]; onClose: () => void; onSave: (draft: { title: string; parentId: string | null; body?: string; duePreset?: DuePreset; dueAt?: Date | null; status?: 'active' | 'completed' }) => void }) {
  const styles = useStyles(); const { colors } = useAppTheme();
  const memo = editor?.node?.type === 'memo' ? editor.node : null; const dueContext = editor?.dueContext; const [title, setTitle] = useState(editor?.node?.title ?? ''); const [body, setBody] = useState(memo?.body ?? ''); const [preset, setPreset] = useState<DuePreset>(memo?.duePreset ?? dueContext?.initialDuePreset ?? 'today'); const [custom, setCustom] = useState(() => formatDateTimeInput(memo?.dueAt ?? dueContext?.initialDueAt ?? new Date())); const [status, setStatus] = useState<'active' | 'completed'>(memo?.status ?? 'active');
  const save = () => { if (!editor || !title.trim()) return appAlert('入力エラー', 'タイトルは必須です。'); let dueAt = dueContext && !dueContext.dueEditable ? dueContext.initialDueAt : dueDateForPreset(preset); if (preset === 'custom' && !dueContext) { dueAt = parseLocalDateTime(custom); if (!dueAt) return appAlert('入力エラー', '日時を YYYY/MM/DD HH:mm 形式で入力してください。'); } if (dueContext?.dueEditable && deadlineGroupForDueAt(dueAt, new Date(), dueContext.granularity) !== dueContext.targetGroup) return appAlert('入力エラー', `「${dueContext.label}」に入る期限を指定してください。`); onSave({ title, parentId: editor.parentId, body, duePreset: dueContext?.initialDuePreset ?? preset, dueAt, status }); };
  return <Modal visible={!!editor} animationType="slide" presentationStyle="pageSheet" allowSwipeDismissal onRequestClose={onClose}>
    <SafeAreaView style={styles.modalPage}><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
      <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.form}>
        <View style={styles.grabber} /><Text style={styles.modalTitle}>{editor?.node ? '編集' : '新規作成'}</Text>
        {editor?.type === 'memo' && <Text style={styles.destination}>追加先: {categoryPath(nodes, editor.parentId)} · 期限: {dueContext?.label ?? presets.find((item) => item.key === preset)?.label}</Text>}
        <Text style={styles.label}>{editor?.type === 'memo' ? 'タイトル' : 'Category名'} *</Text><TextInput value={title} onChangeText={setTitle} placeholderTextColor={colors.textSecondary} style={styles.input} autoFocus />
        {editor?.type === 'memo' && <><Text style={styles.label}>自由記述</Text><TextInput value={body} onChangeText={setBody} placeholderTextColor={colors.textSecondary} style={[styles.input, styles.multiline]} multiline textAlignVertical="top" /><Text style={styles.label}>期限</Text>{dueContext ? dueContext.dueEditable ? <DateTimeField value={custom} onChange={setCustom} /> : <Text style={styles.lockedDue}>{presets.find((item) => item.key === preset)?.label}</Text> : <><View style={styles.chips}>{presets.map((item) => <Pressable key={item.key} onPress={() => setPreset(item.key)} style={[styles.chip, preset === item.key && styles.chipOn]}><Text style={[styles.chipText, preset === item.key && styles.chipTextOn]}>{item.label}</Text></Pressable>)}</View>{preset === 'custom' && <DateTimeField value={custom} onChange={setCustom} />}</>}{memo && <><Text style={styles.label}>ステータス</Text><View style={styles.chips}><Pressable onPress={() => setStatus('active')} style={[styles.chip, status === 'active' && styles.chipOn]}><Text style={styles.chipText}>未完了</Text></Pressable><Pressable onPress={() => setStatus('completed')} style={[styles.chip, status === 'completed' && styles.chipOn]}><Text style={styles.chipText}>完了</Text></Pressable></View></>}</>}
        <View style={styles.formButtons}><Pressable onPress={onClose} style={styles.secondary}><Text style={styles.buttonText}>キャンセル</Text></Pressable><Pressable onPress={save} style={styles.primary}><Text style={styles.primaryText}>保存</Text></Pressable></View>
      </ScrollView>
    </KeyboardAvoidingView></SafeAreaView>
  </Modal>;
}

function FullScreenModalPage({ children }: { children: React.ReactNode }) {
  const insets = useSafeAreaInsets(); const styles = useStyles();
  return <View style={[styles.modalPage, { paddingTop: insets.top, paddingRight: insets.right, paddingBottom: insets.bottom, paddingLeft: insets.left }]}>{children}</View>;
}

function ListPanel({ type, nodes, parentName, onClose, onRestore, onDelete, onHardDelete, onReset }: { type: Panel; nodes: Node[]; parentName: (id: string | null) => string; onClose: () => void; onRestore: (id: string, completed: boolean) => void; onDelete: (id: string) => void; onHardDelete: (id: string) => void; onReset: () => void }) {
  const styles = useStyles(); const [criterion, setCriterion] = useState<CompletionHistoryCriterion>('completedAt');
  const historyGroups = useMemo(() => completionHistoryGroups(nodes, criterion), [criterion, nodes]);
  const trashItems = useMemo(() => nodes.filter((node) => node.deletedAt && !node.purgedAt).sort((a, b) => b.deletedAt!.getTime() - a.deletedAt!.getTime()), [nodes]);
  return <Modal visible={!!type} animationType="slide" onRequestClose={onClose}>
    <FullScreenModalPage>
      <View style={styles.panelHeader}><Text style={styles.modalTitle}>{type === 'completed' ? '完了一覧' : 'ゴミ箱'}</Text><Pressable onPress={onClose} style={styles.close} accessibilityRole="button" accessibilityLabel={`${type === 'completed' ? '完了一覧' : 'ゴミ箱'}を閉じる`}><Text style={styles.buttonText}>閉じる</Text></Pressable></View>
      {type === 'completed' && <View style={styles.historyCriteria}>{COMPLETION_HISTORY_CRITERIA.map((item) => <Pressable key={item.id} onPress={() => setCriterion(item.id)} style={[styles.historyCriterion, criterion === item.id && styles.historyCriterionActive]}><Text style={[styles.buttonText, criterion === item.id && styles.historyCriterionTextActive]}>{item.label}</Text></Pressable>)}</View>}
      <ScrollView contentContainerStyle={styles.panelList}>{type === 'completed' ? <>{historyGroups.length === 0 && <Text style={styles.empty}>項目はありません</Text>}{historyGroups.map((group) => <View key={group.key}><Text style={styles.historyHeading}>{group.label}</Text>{group.memos.map((memo) => <View key={memo.id} style={styles.panelCard}><Text style={styles.cardTitle}>✓ {memo.title}</Text><Text style={styles.meta}>元: {parentName(memo.parentId)}</Text><View style={styles.cardActions}><Pressable onPress={() => onRestore(memo.id, true)} style={styles.smallButton}><Text style={styles.buttonText}>未完了へ戻す</Text></Pressable><Pressable onPress={() => onDelete(memo.id)} style={styles.smallButton}><Text style={styles.danger}>削除</Text></Pressable></View></View>)}</View>)}</> : <>{trashItems.length === 0 && <Text style={styles.empty}>項目はありません</Text>}{trashItems.map((node) => <View key={node.id} style={styles.panelCard}><Text style={styles.cardTitle}>{node.title}</Text><Text style={styles.meta}>{node.type === 'memo' ? 'Memo' : 'Category'} · 元: {parentName(node.parentId)}</Text><Text style={styles.meta}>{node.deletedAt?.toLocaleString()}</Text><View style={styles.cardActions}><Pressable onPress={() => onRestore(node.id, false)} style={styles.smallButton}><Text style={styles.buttonText}>復元</Text></Pressable><Pressable onPress={() => onHardDelete(node.id)} style={styles.smallButton}><Text style={styles.danger}>完全削除</Text></Pressable></View></View>)}</>}</ScrollView>
      {type === 'trash' && <Pressable onPress={onReset} style={styles.reset}><Text style={styles.danger}>データを初期化</Text></Pressable>}
    </FullScreenModalPage>
  </Modal>;
}

function SnackbarNotice({ notice, onExpire, onUndo }: { notice: { id: string; title: string }; onExpire: () => void; onUndo: () => void }) {
  const styles = useStyles(); const expireRef = useRef(onExpire);
  useEffect(() => { expireRef.current = onExpire; }, [onExpire]);
  useEffect(() => { const timer = setTimeout(() => expireRef.current(), 5000); return () => clearTimeout(timer); }, []);
  return <View style={styles.snackbar}><Text style={styles.snackbarText}>✓ 「{notice.title}」を完了しました</Text><Pressable onPress={onUndo} style={styles.snackbarUndo}><Text style={styles.snackbarUndoText}>元に戻す</Text></Pressable></View>;
}

function MovePanel({ node, nodes, onClose, onMove }: { node: Node | null; nodes: Node[]; onClose: () => void; onMove: (parentId: string | null) => void }) { const styles = useStyles(); const categories = nodes.filter((item) => item.type === 'category' && item.deletedAt === null && !!node && canMoveNode(nodes, node.id, item.id)); return <Modal visible={!!node} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><SafeAreaView style={styles.modalPage}><View style={styles.panelHeader}><Text style={styles.modalTitle}>移動先</Text><Pressable onPress={onClose} style={styles.close}><Text style={styles.actionText}>閉じる</Text></Pressable></View><ScrollView contentContainerStyle={styles.panelList}><Action label="ルート" onPress={() => onMove(null)} />{categories.map((category) => <Action key={category.id} label={category.title} onPress={() => onMove(category.id)} />)}</ScrollView></SafeAreaView></Modal>; }

function BulkMovePanel({ memoIds, nodes, onClose, onMove }: { memoIds: string[]; nodes: Node[]; onClose: () => void; onMove: (parentId: string | null) => void }) { const styles = useStyles(); const categories = nodes.filter((item) => item.type === 'category' && item.deletedAt === null && !item.purgedAt); return <Modal visible={memoIds.length > 0} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><SafeAreaView style={styles.modalPage}><View style={styles.panelHeader}><Text style={styles.modalTitle}>{memoIds.length}件の移動先</Text><Pressable onPress={onClose} style={styles.close}><Text style={styles.actionText}>閉じる</Text></Pressable></View><ScrollView contentContainerStyle={styles.panelList}><Action label="ルート" onPress={() => onMove(null)} />{categories.map((category) => <Action key={category.id} label={category.title} onPress={() => onMove(category.id)} />)}</ScrollView></SafeAreaView></Modal>; }

function useStyles() { return createStyles(useAppTheme().colors); }
const createStyles = (colors: ThemeColors) => StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background }, tree: { flex: 1 },
  header: { paddingHorizontal: 20, paddingVertical: 10, backgroundColor: colors.surface, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, headerActions: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  title: { color: colors.text, fontSize: 25, fontWeight: '700' }, subtitle: { color: colors.textSecondary, fontSize: 11 },
  historyButton: { width: 38, minHeight: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 9, backgroundColor: colors.surfaceAlt }, historyText: { color: colors.accent, fontSize: 23 }, disabled: { opacity: 0.3 },
  tabs: { flexDirection: 'row', paddingHorizontal: 10, borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth, backgroundColor: colors.surface }, tab: { flex: 1, minHeight: 40, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' }, tabActive: { borderBottomColor: colors.accent }, tabText: { color: colors.textSecondary, fontSize: 13 }, tabTextActive: { color: colors.text, fontWeight: '700' },
  topButton: { minHeight: 38, paddingHorizontal: 9, justifyContent: 'center' }, topText: { color: colors.textSecondary, fontSize: 13, fontWeight: '600' },
  fab: { position: 'absolute', right: 22, bottom: 24, width: 58, height: 58, alignItems: 'center', justifyContent: 'center', borderRadius: 29, backgroundColor: colors.accent, elevation: 6, shadowOpacity: .2, shadowRadius: 8 }, fabText: { color: colors.background, fontSize: 34, fontWeight: '300', marginTop: -3 },
  backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: colors.backdrop }, sheet: { maxHeight: '88%', padding: 18, paddingBottom: 28, borderTopLeftRadius: 22, borderTopRightRadius: 22, backgroundColor: colors.surface }, sheetContent: { flexGrow: 0 }, sheetTitle: { marginBottom: 10, color: colors.text, fontSize: 19, fontWeight: '700' }, settingsHeading: { marginTop: 12, paddingBottom: 5, color: colors.textSecondary, fontSize: 12, fontWeight: '700' }, action: { minHeight: 50, justifyContent: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, actionText: { color: colors.text, fontSize: 16 }, danger: { color: colors.danger }, buttonText: { color: colors.text },
  modalPage: { flex: 1, backgroundColor: colors.background }, form: { padding: 22, paddingBottom: 50 }, grabber: { width: 42, height: 5, alignSelf: 'center', marginBottom: 12, borderRadius: 3, backgroundColor: colors.border }, modalTitle: { color: colors.text, fontSize: 25, fontWeight: '700' }, destination: { marginTop: 7, color: colors.textSecondary, fontSize: 12 }, label: { marginTop: 20, marginBottom: 7, color: colors.textSecondary, fontSize: 13, fontWeight: '700' }, input: { minHeight: 48, paddingHorizontal: 13, borderWidth: 1, borderColor: colors.border, borderRadius: 11, backgroundColor: colors.surface, color: colors.text, fontSize: 16 }, multiline: { minHeight: 130, paddingTop: 12 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { minHeight: 40, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center', borderRadius: 20, backgroundColor: colors.surfaceAlt }, chipOn: { backgroundColor: colors.accentSoft }, chipText: { color: colors.text }, chipTextOn: { color: colors.accent, fontWeight: '700' }, lockedDue: { minHeight: 48, paddingHorizontal: 13, paddingVertical: 14, borderRadius: 11, backgroundColor: colors.surfaceAlt, color: colors.textSecondary }, formButtons: { marginTop: 30, flexDirection: 'row', gap: 12 }, secondary: { flex: 1, minHeight: 50, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: colors.surfaceAlt }, primary: { flex: 1, minHeight: 50, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: colors.accent }, primaryText: { color: colors.background, fontWeight: '700' },
  panelHeader: { padding: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.surface }, close: { minHeight: 44, minWidth: 56, justifyContent: 'center', alignItems: 'center' }, historyCriteria: { marginHorizontal: 16, marginTop: 10, padding: 3, flexDirection: 'row', borderRadius: 10, backgroundColor: colors.surfaceAlt }, historyCriterion: { flex: 1, minHeight: 36, alignItems: 'center', justifyContent: 'center', borderRadius: 8 }, historyCriterionActive: { backgroundColor: colors.surface }, historyCriterionTextActive: { color: colors.accent, fontWeight: '700' }, historyHeading: { marginTop: 14, marginBottom: 7, paddingBottom: 5, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, color: colors.textSecondary, fontSize: 14, fontWeight: '700' }, panelList: { padding: 16, paddingBottom: 80 }, empty: { padding: 30, textAlign: 'center', color: colors.textSecondary }, panelCard: { marginBottom: 10, padding: 15, borderRadius: 12, backgroundColor: colors.surface }, cardTitle: { color: colors.text, fontSize: 16, fontWeight: '700' }, meta: { marginTop: 4, color: colors.textSecondary, fontSize: 12 }, cardActions: { marginTop: 12, flexDirection: 'row', gap: 10 }, smallButton: { minHeight: 40, paddingHorizontal: 12, justifyContent: 'center', borderRadius: 9, backgroundColor: colors.surfaceAlt }, reset: { position: 'absolute', bottom: 18, alignSelf: 'center', padding: 14, borderRadius: 10, backgroundColor: colors.surface },
  snackbarStack: { position: 'absolute', left: 16, right: 16, bottom: 92, gap: 7 }, snackbar: { minHeight: 52, paddingLeft: 15, paddingRight: 6, flexDirection: 'row', alignItems: 'center', borderRadius: 12, backgroundColor: colors.snackbarBackground, elevation: 8, shadowOpacity: .25, shadowRadius: 8 }, snackbarText: { flex: 1, color: colors.snackbarText, fontSize: 13 }, snackbarUndo: { minHeight: 44, paddingHorizontal: 12, justifyContent: 'center' }, snackbarUndoText: { color: colors.snackbarAction, fontWeight: '800' },
});
